# A Test Dockerfile to test integration to Azure
FROM mrc.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /app

# copy work to /app directory
COPY . .
RUN dotnet restore

# Build application
RUN dotnet build --no-restore -c Release

# Skips build process.
# Used for trying to integrate with Azure and not debugging c# code.
CMD ["dotnet", "test", "--no-build", "--logger:trx"]