name: Dependency Audit

on:
  push:
    branches:
        - main

jobs:
  dependency-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install .NET 9.0 SDK using setup-dotnet
      - name: Set up .NET 9.0 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'  # Use a stable or preview version of .NET 9.0

      # Step to restore dependencies
      - name: Restore dependencies
        run: dotnet restore /home/runner/work/Docker-FileOrganize/Docker-FileOrganize/FileOrganizer.csproj

      # Step to check dotnet for vulnerable packages
      - name: Check dotnet for vulnerable packages
        id: check-dependencies
        run: |
          dependencies=$(dotnet list package --vulnerable)
          if [[ -n "$dependencies" ]]; then
            echo "Vulnerable packages found."
            echo "$dependencies"
            echo "vulnerable=true" >> $GITHUB_ENV  # Sets environment variable
          else
            echo "No vulnerable packages found."
            echo "vulnerable=false" >> $GITHUB_ENV  # Sets environment variable
          fi
